fill_md: fill_md.d
	rdmd --build-only -IBioD -O -release -inline fill_md.d

filter_unique: filter_unique.d
	rdmd --build-only -IBioD -O -release -inline filter_unique.d

read_bam: read_bam.d
	rdmd --build-only -IBioD -O -release -inline read_bam.d

count_mean_coverage: count_mean_coverage.d
	rdmd --build-only -IBioD -O -release -inline count_mean_coverage.d
